name: parking_monitor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # カメラ機能
  camera: ^0.10.5+9
  
  # メール送信
  mailer: ^6.1.0
  
  # 設定保存
  shared_preferences: ^2.2.2
  
  # 権限管理
  permission_handler: ^11.3.0
  
  # ファイルパス操作
  path: ^1.8.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  transparent_image: ^2.0.1
  video_player: ^2.8.3
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
